name: Gradle Tests (Java 21)

on:
  push:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: List directory contents
        run: ls -la

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Run Gradle tests
        run: ./gradlew test

      - name: Create ZIP of entire build directory
        run: zip -r build-folder.zip build

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-folder
          path: build-folder.zip